/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get portfolio snapshot
         * @description Returns an aggregated health snapshot for all projects in a single call.
         *     Designed for the Portfolio View — shows next version progress, next proposed
         *     feature, in-progress features (capped at 5), blocked features, and recent
         *     completions (last 7 days) for each project.
         */
        get: operations["getPortfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscribe to portfolio change events (SSE)
         * @description Server-sent event stream that fires a `change` event whenever any feature
         *     in any project is modified. The client should re-fetch `GET /portfolio` on
         *     each event. No payload is included — the data endpoint does the work.
         *
         *     Reuses the same global broadcast channel as the per-project SSE streams.
         *     One connection covers all projects regardless of how many exist.
         */
        get: operations["subscribePortfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesystem/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse directories
         * @description Lists subdirectories at a given path for building a directory browser UI.
         *     Skips hidden directories and common noise directories (node_modules, target, etc.).
         *     Defaults to the user's home directory if no path is provided.
         *     Only available on the local self-hosted server.
         */
        get: operations["browseFilesystem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesystem/mkdir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a directory
         * @description Creates a directory at the specified path, including intermediate
         *     directories. Idempotent — succeeds if the directory already exists.
         *     Safety guarantees:
         *     - Path must be absolute
         *     - Path must not contain '..' components
         *     - Subject to the same path restrictions as browsing
         */
        post: operations["createDirectory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all projects */
        get: operations["listProjects"];
        put?: never;
        /** Create a new project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/by-directory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find project by directory path
         * @description Given a directory path, finds the project that contains it.
         *     Matches if the path equals or is a subdirectory of any project directory.
         *     Useful for MCP clients to discover project context from the current working directory.
         */
        get: operations["getProjectByDirectory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Project slug (URL-friendly identifier)
                 * @example manifest
                 */
                slug: string;
            };
            cookie?: never;
        };
        /** Get a project by slug */
        get: operations["getProjectBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** Get a project with its directories */
        get: operations["getProject"];
        /** Update a project */
        put: operations["updateProject"];
        post?: never;
        /**
         * Delete a project
         * @description Deletes the project and cascades to all features, sessions, and tasks
         */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/focus": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /**
         * Get focused feature for project
         * @description Returns the currently focused feature for the project (used by MCP agents to know what the user is looking at).
         */
        get: operations["getProjectFocus"];
        /** Set or clear focused feature for project */
        put: operations["setProjectFocus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /**
         * Get project-wide history
         * @description Returns history entries across all features in the project, ordered by
         *     creation date (newest first). Each entry includes feature and version context.
         *     Useful for PMs to see recent changes across the entire project.
         *     Filter by version_id to see all work done for a specific release.
         */
        get: operations["getProjectHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/directories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** List project directories */
        get: operations["listProjectDirectories"];
        put?: never;
        /** Add a directory to a project */
        post: operations["addProjectDirectory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** List versions for a project */
        get: operations["listProjectVersions"];
        put?: never;
        /** Create a new version */
        post: operations["createVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Version UUID */
                id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        /** Get a version by ID */
        get: operations["getVersion"];
        /** Update a version */
        put: operations["updateVersion"];
        post?: never;
        /** Delete a version */
        delete: operations["deleteVersion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/features": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /**
         * List all features in a project
         * @description Returns feature summaries ordered by priority then title.
         *     Always returns summaries only - use GET /features/{id} for full details.
         */
        get: operations["listProjectFeatures"];
        put?: never;
        /** Create a feature in a project */
        post: operations["createFeature"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/features/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk create features with hierarchical structure
         * @description Create multiple features at once, supporting hierarchical relationships.
         *     Use this to set up an entire feature tree in one operation.
         *
         *     When `confirm=false` (default), returns the proposed features without creating them.
         *     This allows reviewing the structure before committing.
         *
         *     When `confirm=true`, creates all features and returns their IDs.
         *     Children are created after their parents, maintaining the tree structure.
         */
        post: operations["bulkCreateFeatures"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/features/roots": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** List root features (no parent) in a project */
        get: operations["listRootFeatures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/features/tree": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /**
         * Get complete feature tree
         * @description Returns all features in a hierarchical tree structure with children
         *     recursively nested. Useful for visualizing the full project structure.
         */
        get: operations["getFeatureTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/directories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Directory UUID */
                id: components["parameters"]["DirectoryId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a directory */
        delete: operations["removeProjectDirectory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all features across all projects
         * @description Returns feature summaries ordered by priority then title.
         *     Always returns summaries only - use GET /features/{id} for full details.
         */
        get: operations["listFeatures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search features by title or content
         * @description Search features by matching against title and details.
         *     Returns summaries ranked by relevance (title matches first).
         *     Use GET /features/{id} for full details of a specific result.
         */
        get: operations["searchFeatures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feature UUID */
                id: components["parameters"]["FeatureId"];
            };
            cookie?: never;
        };
        /** Get a feature by ID */
        get: operations["getFeature"];
        /** Update a feature */
        put: operations["updateFeature"];
        post?: never;
        /**
         * Delete a feature
         * @description Deletes the feature and cascades to all children
         */
        delete: operations["deleteFeature"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/{id}/children": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feature UUID */
                id: components["parameters"]["FeatureId"];
            };
            cookie?: never;
        };
        /** List direct children of a feature */
        get: operations["listChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feature UUID */
                id: components["parameters"]["FeatureId"];
            };
            cookie?: never;
        };
        /**
         * Get feature history
         * @description Returns the implementation history log (like git log)
         */
        get: operations["getFeatureHistory"];
        put?: never;
        /**
         * Add a history entry to a feature
         * @description Records work completed on a feature. Each entry captures a summary of changes
         *     and optionally links to git commits. Use this when completing work on a feature.
         */
        post: operations["addFeatureHistory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/{id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feature UUID */
                id: components["parameters"]["FeatureId"];
            };
            cookie?: never;
        };
        /**
         * Get feature diff
         * @description Returns the diff between current details and desired details.
         *     Use this to see what changes are pending before implementation.
         */
        get: operations["getFeatureDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/{id}/blockers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feature UUID */
                id: components["parameters"]["FeatureId"];
            };
            cookie?: never;
        };
        /**
         * Get feature blockers
         * @description Returns the features that are blocking this feature.
         *     Only returns results for features in the 'blocked' state.
         */
        get: operations["getFeatureBlockers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Project: {
            /** Format: uuid */
            id: string;
            /**
             * @description URL-friendly identifier (lowercase, hyphenated). Unique across all projects.
             * @example manifest
             */
            slug: string;
            /**
             * @description Uppercase prefix for human-friendly feature IDs (e.g., "MAN" produces MAN-1, MAN-2). Auto-derived from slug, max 5 chars.
             * @example MAN
             */
            key_prefix: string;
            /** @example Manifest */
            name: string;
            /** @example Living feature documentation server */
            description?: string | null;
            /**
             * @description Project-wide instructions for AI agents (coding guidelines, conventions, etc.)
             * @example Use Result<T,E> for errors. Follow coding-guidelines.md.
             */
            instructions?: string | null;
            /**
             * Format: uuid
             * @description ID of the current/active version for this project
             */
            current_version_id?: string | null;
            /**
             * @description Where new features go by default. "backlog" leaves them unassigned, "now" assigns to the current version.
             * @default backlog
             * @enum {string}
             */
            default_feature_destination: "backlog" | "now";
            /**
             * @description How detailed guidance should be for feature sets and project context.
             * @default standard
             * @enum {string}
             */
            detail_level: "concise" | "standard" | "thorough";
            /**
             * @description How detailed guidance should be for leaf feature specifications.
             * @default standard
             * @enum {string}
             */
            ac_level: "concise" | "standard" | "thorough";
            /**
             * @description Output format for acceptance criteria.
             * @default checkbox
             * @enum {string}
             */
            ac_format: "checkbox" | "gherkin";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateProjectInput: {
            /** @example My Project */
            name: string;
            /**
             * @description URL-friendly identifier. If not provided, auto-generated from name.
             * @example my-project
             */
            slug?: string | null;
            /**
             * @description Uppercase prefix for feature display IDs (max 5 chars). Auto-derived from slug if not provided.
             * @example MYPRJ
             */
            key_prefix?: string | null;
            description?: string | null;
            /** @description Project-wide instructions for AI agents */
            instructions?: string | null;
        };
        UpdateProjectInput: {
            name?: string;
            /**
             * @description URL-friendly identifier. Must be unique.
             * @example my-project
             */
            slug?: string;
            /**
             * @description Uppercase prefix for feature display IDs (max 5 chars).
             * @example MYPRJ
             */
            key_prefix?: string;
            description?: string | null;
            /** @description Project-wide instructions for AI agents */
            instructions?: string | null;
            /**
             * Format: uuid
             * @description Set the current/active version for this project
             */
            current_version_id?: string | null;
            /**
             * @description Where new features go by default. "backlog" leaves them unassigned, "now" assigns to the current version.
             * @enum {string}
             */
            default_feature_destination?: "backlog" | "now";
            /**
             * @description How detailed guidance should be for feature sets and project context.
             * @enum {string}
             */
            detail_level?: "concise" | "standard" | "thorough";
            /**
             * @description How detailed guidance should be for leaf feature specifications.
             * @enum {string}
             */
            ac_level?: "concise" | "standard" | "thorough";
            /**
             * @description Output format for acceptance criteria.
             * @enum {string}
             */
            ac_format?: "checkbox" | "gherkin";
        };
        ProjectDirectory: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            /** @example /Users/dev/projects/my-project */
            path: string;
            /** @example git@github.com:org/repo.git */
            git_remote?: string | null;
            /** @default false */
            is_primary: boolean;
            /**
             * @description Directory-specific instructions for AI agents (build commands, test commands, etc.)
             * @example Run tests with: cargo test. Build with: cargo build --release
             */
            instructions?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        AddDirectoryInput: {
            /** @example /Users/dev/projects/my-project */
            path: string;
            git_remote?: string | null;
            /** @default false */
            is_primary: boolean;
            /** @description Directory-specific instructions for AI agents */
            instructions?: string | null;
        };
        ProjectWithDirectories: {
            /** Format: uuid */
            id: string;
            /** @description URL-friendly identifier */
            slug: string;
            name: string;
            description?: string | null;
            /** @description Project-wide instructions for AI agents */
            instructions?: string | null;
            /**
             * Format: uuid
             * @description ID of the current/active version for this project
             */
            current_version_id?: string | null;
            /**
             * @description Where new features go by default. "backlog" leaves them unassigned, "now" assigns to the current version.
             * @default backlog
             * @enum {string}
             */
            default_feature_destination: "backlog" | "now";
            /**
             * @description How detailed guidance should be for feature sets and project context.
             * @default standard
             * @enum {string}
             */
            detail_level: "concise" | "standard" | "thorough";
            /**
             * @description How detailed guidance should be for leaf feature specifications.
             * @default standard
             * @enum {string}
             */
            ac_level: "concise" | "standard" | "thorough";
            /**
             * @description Output format for acceptance criteria.
             * @default checkbox
             * @enum {string}
             */
            ac_format: "checkbox" | "gherkin";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            directories: components["schemas"]["ProjectDirectory"][];
        };
        Feature: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            /**
             * Format: uuid
             * @description Parent feature ID (null for root features)
             */
            parent_id?: string | null;
            /** @example User Authentication */
            title: string;
            /** @description Current feature specification (what the feature IS) */
            details?: string | null;
            /** @description Desired feature specification (what the feature SHOULD be). Non-null indicates pending changes. */
            desired_details?: string | null;
            state: components["schemas"]["FeatureState"];
            /**
             * @description Priority for ordering within parent (lower values first)
             * @default 0
             */
            priority: number;
            /** @description Per-project sequential number for display IDs (e.g., 42 in MAN-42). Assigned at creation time. */
            feature_number?: number | null;
            /**
             * Format: uuid
             * @description Target version ID for release planning
             */
            target_version_id?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description - proposed: Initial state, in backlog
         *     - blocked: Cannot proceed until blocker features are implemented
         *     - in_progress: Actively being worked on
         *     - implemented: Feature is live in codebase
         *     - archived: Feature archived (soft-deleted)
         * @enum {string}
         */
        FeatureState: "proposed" | "blocked" | "in_progress" | "implemented" | "archived";
        /** @description Lightweight feature summary without details (used for list operations) */
        FeatureSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            /**
             * Format: uuid
             * @description Parent feature ID (null for root features)
             */
            parent_id?: string | null;
            /** @example User Authentication */
            title: string;
            state: components["schemas"]["FeatureState"];
            /**
             * @description Priority for ordering within parent (lower values first)
             * @default 0
             */
            priority: number;
            /**
             * Format: uuid
             * @description Target version ID for release planning
             */
            target_version_id?: string | null;
        };
        CreateFeatureInput: {
            /** Format: uuid */
            parent_id?: string | null;
            title: string;
            /** @description Feature specification including user stories, implementation notes, and technical context */
            details?: string | null;
            state?: components["schemas"]["FeatureState"];
            /**
             * Format: uuid
             * @description Target version for release planning
             */
            target_version_id?: string | null;
        };
        UpdateFeatureInput: {
            title?: string;
            /** @description Current feature specification (what the feature IS) */
            details?: string | null;
            /** @description Desired feature specification (what the feature SHOULD be). Set to plan pending changes. */
            desired_details?: string | null;
            state?: components["schemas"]["FeatureState"];
            /** @description Priority for ordering within parent */
            priority?: number;
            /**
             * Format: uuid
             * @description Target version for release planning
             */
            target_version_id?: string | null;
            /**
             * Format: uuid
             * @description Move feature under a different parent. Set null to make root-level.
             */
            parent_id?: string | null;
            /** @description Feature IDs that block this feature. Required when transitioning to 'blocked' state. The feature auto-transitions to 'proposed' when all blockers reach 'implemented'. */
            blocked_by?: string[];
        };
        /** @description Input for bulk feature creation with hierarchical structure */
        BulkCreateFeaturesInput: {
            /** @description The proposed feature tree to create */
            features: components["schemas"]["ProposedFeature"][];
            /**
             * @description If true, creates the features in the database.
             *     If false (default), returns the proposal for review without creating anything.
             * @default false
             */
            confirm: boolean;
        };
        /** @description A feature proposal for bulk creation, supporting hierarchical structure */
        ProposedFeature: {
            /**
             * @description Short capability name (2-5 words). What users can DO.
             * @example User Authentication
             */
            title: string;
            /**
             * @description Feature details including user stories, implementation notes, and technical context.
             *     User stories can use "As a [user], I can [capability] so that [benefit]" format.
             */
            details?: string | null;
            /**
             * @description Priority for ordering. Lower values = implement first.
             * @default 0
             */
            priority: number;
            /**
             * @description Child features (for hierarchical structure)
             * @default []
             */
            children: components["schemas"]["ProposedFeature"][];
        };
        /** @description Response from bulk feature creation */
        PlanFeaturesResponse: {
            /** @description The proposed feature tree (same as input, for review) */
            proposed_features: components["schemas"]["ProposedFeature"][];
            /** @description Whether the features were created (true if confirm=true was passed) */
            created: boolean;
            /**
             * @description UUIDs of created features (only populated if created=true)
             * @default []
             */
            created_feature_ids: string[];
        };
        /** @description A feature with its children recursively nested */
        FeatureTreeNode: components["schemas"]["Feature"] & {
            children: components["schemas"]["FeatureTreeNode"][];
            /**
             * @description True if this is the project's root feature (contains project instructions)
             * @default false
             */
            is_root: boolean;
        };
        /**
         * @description Append-only log entry recording work completed on a feature.
         *     Similar to git log - records implementation history, not version snapshots.
         */
        FeatureHistory: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            feature_id: string;
            /**
             * Format: uuid
             * @description Version this work was done for (captured at time of completion)
             */
            version_id?: string | null;
            /** @description Summary of work completed */
            summary: string;
            /** @description Git commits created during this work */
            commits?: components["schemas"]["CommitRef"][];
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description Project-wide history entry with feature context. Used for the unified
         *     project history view, where PMs can see recent changes across all features.
         */
        ProjectHistoryEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            feature_id: string;
            /** @description Feature title, denormalized for display */
            feature_title: string;
            /** @description Feature state at time of query */
            feature_state: components["schemas"]["FeatureState"];
            /**
             * Format: uuid
             * @description Version this work was done for
             */
            version_id?: string | null;
            /** @description Version name, denormalized for display */
            version_name?: string | null;
            /** @description Summary of work completed */
            summary: string;
            /** @description Git commits created during this work */
            commits?: components["schemas"]["CommitRef"][];
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description Diff between current and desired feature details.
         *     Use this to see pending changes before implementation.
         */
        FeatureDiff: {
            /** @description Whether there are pending changes (desired_details differs from details) */
            has_changes: boolean;
            /** @description Current details (what the feature IS) */
            current?: string | null;
            /** @description Desired details (what the feature SHOULD be) */
            desired?: string | null;
        };
        /** @description Input for adding a history entry to a feature */
        AddHistoryInput: {
            /** @description Summary of work completed */
            summary: string;
            /** @description Git commits created during this work */
            commits?: components["schemas"]["CommitRef"][];
            /**
             * Format: uuid
             * @description Version this work was done for (defaults to feature's target_version_id if not specified)
             */
            version_id?: string | null;
        };
        /** @description Reference to a git commit */
        CommitRef: {
            /**
             * @description Commit SHA (short or full)
             * @example abc123f
             */
            sha: string;
            /**
             * @description Commit message (first line)
             * @example Add OAuth login flow
             */
            message: string;
            /** @description Commit author (if different from default) */
            author?: string | null;
        };
        /** @description A version for release planning */
        Version: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            /**
             * @description Version name (e.g., "1.0.0", "2.0.0-beta")
             * @example 1.0.0
             */
            name: string;
            /** @description Optional description of the version */
            description?: string | null;
            /**
             * Format: date-time
             * @description When this version was released (if released)
             */
            released_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateVersionInput: {
            /** @description Version name (e.g., "1.0.0", "2.0.0-beta") */
            name: string;
            /** @description Optional description of the version */
            description?: string | null;
        };
        UpdateVersionInput: {
            /** @description Version name */
            name?: string;
            /** @description Optional description of the version */
            description?: string | null;
            /**
             * Format: date-time
             * @description Set to mark the version as released
             */
            released_at?: string | null;
        };
        /** @description Directory listing for the filesystem browser */
        BrowseResponse: {
            /**
             * @description The absolute path being browsed
             * @example /Users/dev/projects
             */
            path: string;
            /**
             * @description Parent directory path, or null if at filesystem root
             * @example /Users/dev
             */
            parent?: string | null;
            /** @description Subdirectories at this path */
            entries: components["schemas"]["DirectoryEntry"][];
        };
        /** @description A subdirectory entry in the filesystem browser */
        DirectoryEntry: {
            /**
             * @description Directory name
             * @example my-project
             */
            name: string;
            /**
             * @description Full absolute path
             * @example /Users/dev/projects/my-project
             */
            path: string;
            /** @description Whether this directory contains visible subdirectories */
            has_children: boolean;
        };
        /** @description Request to create a directory */
        MkdirRequest: {
            /**
             * @description Absolute path of the directory to create
             * @example /Users/dev/projects/my-new-app
             */
            path: string;
        };
        /** @description Result of creating a directory */
        MkdirResponse: {
            /**
             * @description The absolute path that was created
             * @example /Users/dev/projects/my-new-app
             */
            path: string;
        };
        ErrorResponse: {
            /**
             * @description Error message
             * @example Path must be absolute
             */
            error: string;
        };
        /** @description A minimal feature reference used in portfolio lanes. */
        PortfolioFeatureRef: {
            /** Format: uuid */
            id: string;
            title: string;
        };
        /** @description Version progress summary for the portfolio lane header. */
        PortfolioVersionSummary: {
            /** Format: uuid */
            id: string;
            /** @example v0.2.0 */
            name: string;
            /** @description Total leaf features assigned to this version. */
            feature_count: number;
            /** @description Leaf features in this version with state `implemented`. */
            implemented_count: number;
        };
        /** @description The single next actionable feature for a project. */
        PortfolioNextFeature: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @description Whether this feature is assigned to the next version (vs backlog). */
            in_version: boolean;
        };
        /** @description A recent feature completion for the activity section. */
        PortfolioCompletion: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: date-time */
            completed_at: string;
        };
        /** @description Aggregated health snapshot for a single project in the portfolio view. */
        PortfolioProject: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            next_version?: components["schemas"]["PortfolioVersionSummary"];
            next_feature?: components["schemas"]["PortfolioNextFeature"];
            /** @description Up to 5 in-progress leaf features. */
            in_progress: components["schemas"]["PortfolioFeatureRef"][];
            /** @description Total count of in-progress leaf features (may exceed in_progress.length). */
            in_progress_total: number;
            /** @description All blocked leaf features. */
            blocked: components["schemas"]["PortfolioFeatureRef"][];
            /** @description Total count of blocked leaf features. */
            blocked_count: number;
            /** @description Up to 5 features completed in the last 7 days, newest-first. */
            recent_completions: components["schemas"]["PortfolioCompletion"][];
            /**
             * Format: date-time
             * @description Timestamp of the most recent completion (for stalled detection).
             */
            last_activity_at?: string | null;
        };
        /** @description Full portfolio response — health snapshots for all projects. */
        Portfolio: {
            projects: components["schemas"]["PortfolioProject"][];
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
    };
    parameters: {
        /** @description Project UUID */
        ProjectId: string;
        /** @description Directory UUID */
        DirectoryId: string;
        /** @description Feature UUID */
        FeatureId: string;
        /** @description Version UUID */
        VersionId: string;
        /** @description Maximum number of items to return. */
        Limit: number;
        /** @description Number of items to skip for pagination. */
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portfolio snapshot for all projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
        };
    };
    subscribePortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of portfolio change events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    browseFilesystem: {
        parameters: {
            query?: {
                /**
                 * @description Absolute path to browse. Defaults to user's home directory.
                 * @example /Users/dev/projects
                 */
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowseResponse"];
                };
            };
            /** @description Invalid path (not absolute or not a directory) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access denied (path restricted) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Directory not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createDirectory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MkdirRequest"];
            };
        };
        responses: {
            /** @description Directory created (or already existed) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MkdirResponse"];
                };
            };
            /** @description Invalid path (not absolute or contains '..') */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access denied (path restricted) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of projects ordered by name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectInput"];
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getProjectByDirectory: {
        parameters: {
            query: {
                /**
                 * @description Absolute directory path to look up
                 * @example /Users/dev/projects/my-app/src
                 */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project with directories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectWithDirectories"];
                };
            };
            /** @description No project found for the given directory */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getProjectBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Project slug (URL-friendly identifier)
                 * @example manifest
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project with directories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectWithDirectories"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project with directories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectWithDirectories"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectInput"];
            };
        };
        responses: {
            /** @description Project updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getProjectFocus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Focused feature info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        feature_id: string;
                        feature_title: string;
                        feature_state: string;
                    };
                };
            };
            /** @description No feature is focused */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    setProjectFocus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description Feature ID to focus on, or null to clear focus.
                     */
                    feature_id?: string | null;
                };
            };
        };
        responses: {
            /** @description Focus updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProjectHistory: {
        parameters: {
            query?: {
                /** @description Filter to entries for a specific version (useful for release notes). */
                version_id?: string;
                /** @description Maximum number of entries to return. Defaults to 50. */
                limit?: number;
                /** @description Number of entries to skip for pagination. Defaults to 0. */
                offset?: number;
                /** @description Only return entries created after this ISO datetime. */
                since?: string;
            };
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description History entries with feature and version context */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectHistoryEntry"][];
                };
            };
        };
    };
    listProjectDirectories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of directories (primary first, then by path) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDirectory"][];
                };
            };
        };
    };
    addProjectDirectory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddDirectoryInput"];
            };
        };
        responses: {
            /** @description Directory added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDirectory"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listProjectVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of versions ordered by creation date */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"][];
                };
            };
        };
    };
    createVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVersionInput"];
            };
        };
        responses: {
            /** @description Version created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Version UUID */
                id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Version UUID */
                id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVersionInput"];
            };
        };
        responses: {
            /** @description Version updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Version UUID */
                id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listProjectFeatures: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Number of items to skip for pagination. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feature summaries in the project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureSummary"][];
                };
            };
        };
    };
    createFeature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFeatureInput"];
            };
        };
        responses: {
            /** @description Feature created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feature"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    bulkCreateFeatures: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkCreateFeaturesInput"];
            };
        };
        responses: {
            /** @description Proposed or created features */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanFeaturesResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listRootFeatures: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Root features ordered by title */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feature"][];
                };
            };
        };
    };
    getFeatureTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feature tree with nested children */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureTreeNode"][];
                };
            };
        };
    };
    removeProjectDirectory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Directory UUID */
                id: components["parameters"]["DirectoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listFeatures: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Number of items to skip for pagination. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feature summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureSummary"][];
                };
            };
        };
    };
    searchFeatures: {
        parameters: {
            query: {
                /** @description Search term to match against title and details */
                q: string;
                /** @description Optional project UUID to limit search to */
                project_id?: string;
                /** @description Maximum number of results to return. Defaults to 10. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feature summaries matching the search query, ranked by relevance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureSummary"][];
                };
            };
        };
    };
    getFeature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feature UUID */
                id: components["parameters"]["FeatureId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The feature */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feature"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateFeature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feature UUID */
                id: components["parameters"]["FeatureId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFeatureInput"];
            };
        };
        responses: {
            /** @description Feature updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feature"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteFeature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feature UUID */
                id: components["parameters"]["FeatureId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feature deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listChildren: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feature UUID */
                id: components["parameters"]["FeatureId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Direct children ordered by title */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feature"][];
                };
            };
        };
    };
    getFeatureHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feature UUID */
                id: components["parameters"]["FeatureId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description History entries in reverse chronological order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureHistory"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    addFeatureHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feature UUID */
                id: components["parameters"]["FeatureId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddHistoryInput"];
            };
        };
        responses: {
            /** @description History entry created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureHistory"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getFeatureDiff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feature UUID */
                id: components["parameters"]["FeatureId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Diff between current and desired state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureDiff"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getFeatureBlockers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feature UUID */
                id: components["parameters"]["FeatureId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of blocking features */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureSummary"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
